# Generated by Django 5.1.7 on 2025-08-22 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('event_description', models.TextField(verbose_name='Event Description')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Event Date')),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], default='Info', max_length=10, verbose_name='Severity')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date'],
            },
        ),
    ]
