# Generated by Django 5.1.7 on 2025-04-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('event_type', models.CharField(max_length=100, verbose_name='Event Type')),
                ('event_description', models.TextField(verbose_name='Event Description')),
                ('event_date', models.DateTimeField(auto_now_add=True, verbose_name='Event Date')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device', verbose_name='Device')),
            ],
        ),
    ]
