# Generated by Django 5.1.7 on 2025-05-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_options_event_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='severity',
            field=models.CharField(choices=[('Info', 'Info'), ('Warning', 'Warning'), ('Error', 'Error'), ('Critical', 'Critical')], default='Info', max_length=10, verbose_name='Severity'),
        ),
    ]
