# Generated by Django 5.2.5 on 2025-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_type', models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Access Point', 'Access Point'), ('Server', 'Server'), ('Other', 'Other')], max_length=100, verbose_name='Device Type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Maintenance', 'Maintenance'), ('Online', 'Online'), ('Offline', 'Offline'), ('Warning', 'Warning')], default='Active', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_name'],
            },
        ),
    ]
