# Generated by Django 5.1.7 on 2025-04-03 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('device_type', models.CharField(max_length=100, verbose_name='Device Type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('mac_address', models.CharField(max_length=17, verbose_name='MAC Address')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='Status')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Device Owner')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['device_name'],
            },
        ),
    ]
