# Generated by Django 5.2.5 on 2026-08-02 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.PositiveIntegerField(blank=True, help_text='Management/service port (1-65535), if applicable.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Port'),
        ),
    ]
