from django.contrib.auth.models import User
from django.db import models

from apps.devices.models import Device

# Create your models here.

class Report(models.Model):
    report_name = models.CharField(max_length=255, verbose_name="Report Name")

    class ReportType(models.TextChoices):
        PERFORMANCE = 'Performance', 'Performance'
        SECURITY = 'Security', 'Security'
        USAGE = 'Usage', 'Usage'
        AUDIT = 'Audit', 'Audit'
        DEVICE_INVENTORY = 'Device Inventory', 'Device Inventory'
        NETWORK_TOPOLOGY = 'Network Topology', 'Network Topology'
        COMPLIANCE = 'Compliance', 'Compliance'
        CUSTOM = 'Custom', 'Custom'

    
    report_type = models.CharField(choices=ReportType.choices,max_length=100, verbose_name="Report Type")
    report_description = models.TextField(verbose_name="Report Description")
    report_date = models.DateTimeField(auto_now_add=True, verbose_name="Report Date")
    generated_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Generated By",related_name="generated_reports")
    status = models.CharField(max_length=50, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', verbose_name="Status")
    # ForeignKey to Device model
    device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name="Device",related_name="devices")

    def __str__(self):
        return self.report_name
    
    class Meta:
        verbose_name = "Report"
        verbose_name_plural = "Reports"
        ordering = ['-report_date']
        