from django.db import models
from django.contrib.auth.models import User
from apps.devices.models import Device
# Create your models here.

class Report(models.Model):
    report_type = models.CharField(max_length=100, verbose_name="Report Type")
    report_description = models.TextField(verbose_name="Report Description")
    report_date = models.DateTimeField(auto_now_add=True, verbose_name="Report Date")
    generated_by = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Generated By",related_name="generated_reports")
    device = models.ForeignKey(Device, on_delete=models.CASCADE, verbose_name="Device",related_name="devices")