#Generated by 'django-admin startproject' using Django 5.1.7.

'''
Add the apps directory to the Python path
This allows us to import custom apps from the 'apps' directory
now we can import apps from the 'apps' directory just if we type the name of the app
without the need to specify the full path
'''

import os
import sys
from datetime import timedelta
from pathlib import Path

from decouple import config

# ----------------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # This is the base directory of the project
# Add the apps directory to the Python path
sys.path.append(str(BASE_DIR / 'apps'))  # This allows us to import apps from the 'apps' directory
#-----------------------------------------------------------------------------------


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('DJANGO_SECRET_KEY',default='django-insecure-!@#%$^&*()_+1234567890-=qwertyuiopasdfghjklzxcvbnm')

# Application definition
# Custom Apps
MY_CUSTOM_APPS = [
    "apps.users.apps.UsersConfig",
    "apps.events.apps.EventsConfig",
    "apps.devices.apps.DevicesConfig",
    "apps.reports.apps.ReportsConfig",
]
# built in app
INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # ⁡⁣⁢⁣Social Authentication app⁡
    "social_django",
    # rest framework
    "rest_framework",
    # Django rest framwork JWT
    "rest_framework_simplejwt",
    # django widget tweaks
    "widget_tweaks",

]+MY_CUSTOM_APPS

# 𝗦𝗼𝗰𝗶𝗮𝗹 𝗔𝘂𝘁𝗵𝗲𝗻𝘁𝗶𝗰𝗮𝘁𝗶𝗼𝗻 𝗕𝗮𝗰𝗸𝗲𝗻𝗱
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2', 
    'django.contrib.auth.backends.ModelBackend',
)

# 𝗦𝗼𝗰𝗶𝗮𝗹 𝗔𝘂𝘁𝗵 𝗖𝗼𝗻𝗳𝗶𝗴
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config("client_id")
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config("client_secret")
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = 'http://127.0.0.1:8000/oauth/complete/google-oauth2/'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/users/profile/'
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True # This is used to associate the email with the user account
SOCIAL_AUTH_EMAIL_VALIDATION = True # This is used to validate the email address of the user


# 𝗘𝗺𝗮𝗶𝗹 𝗖𝗼𝗻𝗳𝗶𝗴𝗿𝗮𝘁𝗶𝗼𝗻 
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config("EMAIL_HOST_USER") 
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")  
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER 

# JWT Authentication Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  # UI
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': False, 
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

# MIDDLEWARE SECTION
MIDDLEWARE = [
    # Built in Middleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password Hashing Algorithm 
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

PBKDF2_PASSWORD_ITERATIONS = 10000  # Number of iterations for PBKDF2 hashing algorithm

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR , 'staticfiles')
# 𝗠𝗲𝗱𝗶𝗮 𝗳𝗼𝗿 𝗽𝗿𝗼𝗳𝗶𝗹𝗲 𝗽𝗵𝗼𝘁𝗼𝘀
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.CustomUser'
