# Generated by Django 5.2.5 on 2025-09-24 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255, verbose_name='Report Name')),
                ('report_type', models.CharField(choices=[('Performance', 'Performance'), ('Security', 'Security'), ('Usage', 'Usage'), ('Audit', 'Audit'), ('Device Inventory', 'Device Inventory'), ('Network Topology', 'Network Topology'), ('Compliance', 'Compliance'), ('Custom', 'Custom')], max_length=100, verbose_name='Report Type')),
                ('report_description', models.TextField(verbose_name='Report Description')),
                ('report_date', models.DateTimeField(auto_now_add=True, verbose_name='Report Date')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=50, verbose_name='Status')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='devices.device', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
